### ISSUE TITLE
✨ feat: 추천가능 여부 판독 알고리즘

### ISSUE THREAD

**Issue by JiwonHwang84** [Kakaotech-Final-18/Kakaotech-AI#14]
# Title

- 추천가능 여부 판독 알고리즘
- input: 문장단위
- output:추천가능여부

# TODO

- [x] 문장 축적 배열 저장
- [x] 문장 축적 배열 참조
- [x] 추천 가능 여부 반환

# etc

-
